-- Service-orders module (19 §1/§7, CP-1). Generated by drizzle-kit as 0023 and
-- renumbered to 0026 after #108/#109 took 0023–0025 on main. Already applied to
-- the shared Neon DB under the old number, so every statement below is guarded
-- to re-run as a no-op when the migrator replays it under this one.
CREATE TABLE IF NOT EXISTS "service_order_counters" (
	"day" date PRIMARY KEY NOT NULL,
	"last_number" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "service_order_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_order_id" uuid NOT NULL,
	"type" text NOT NULL,
	"actor_id" uuid,
	"ref_kind" text,
	"ref_id" text,
	"changes" jsonb,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "service_order_services" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_order_id" uuid NOT NULL,
	"service_id" uuid NOT NULL,
	"service_name" text NOT NULL,
	"uom" text NOT NULL,
	"tax_rate" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"unit_price" numeric(12, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "service_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"folio" text NOT NULL,
	"customer_id" uuid NOT NULL,
	"location" text,
	"status" text DEFAULT 'open' NOT NULL,
	"comments" text,
	"created_by" uuid NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "services" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"cost" numeric(12, 2),
	"uom" text NOT NULL,
	"description" text,
	"website_description" text,
	"website_image_key" text,
	"internal_service_code" text,
	"tax_rate" text DEFAULT 'iva_16' NOT NULL,
	"sat_prod_serv_code" text,
	"sat_unit_code" text,
	"is_listable_in_website" boolean DEFAULT false NOT NULL,
	"is_price_visible_in_website" boolean DEFAULT false NOT NULL,
	"delete_comment" text,
	"deleted_by" uuid,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "reports_status_check";--> statement-breakpoint
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "service_order_id" uuid;--> statement-breakpoint
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "service_id" uuid;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_order_events" ADD CONSTRAINT "service_order_events_service_order_id_service_orders_id_fk" FOREIGN KEY ("service_order_id") REFERENCES "public"."service_orders"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_order_events" ADD CONSTRAINT "service_order_events_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_order_services" ADD CONSTRAINT "service_order_services_service_order_id_service_orders_id_fk" FOREIGN KEY ("service_order_id") REFERENCES "public"."service_orders"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_order_services" ADD CONSTRAINT "service_order_services_service_id_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_orders" ADD CONSTRAINT "service_orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "service_orders" ADD CONSTRAINT "service_orders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "services" ADD CONSTRAINT "services_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "service_order_events_order_idx" ON "service_order_events" USING btree ("service_order_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "service_order_services_order_idx" ON "service_order_services" USING btree ("service_order_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "service_order_services_order_service_uidx" ON "service_order_services" USING btree ("service_order_id","service_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "service_orders_folio_uidx" ON "service_orders" USING btree ("folio") WHERE "service_orders"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "service_orders_customer_idx" ON "service_orders" USING btree ("customer_id") WHERE "service_orders"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "service_orders_status_idx" ON "service_orders" USING btree ("status") WHERE "service_orders"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "services_name_idx" ON "services" USING btree ("name") WHERE "services"."deleted_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "services_internal_code_uidx" ON "services" USING btree ("internal_service_code") WHERE "services"."internal_service_code" is not null and "services"."deleted_at" is null;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "reports" ADD CONSTRAINT "reports_service_order_id_service_orders_id_fk" FOREIGN KEY ("service_order_id") REFERENCES "public"."service_orders"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "reports" ADD CONSTRAINT "reports_service_id_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_intake_effective_idx" ON "customers" USING btree ((coalesce("status_changed_at", "created_at"))) WHERE "customers"."deleted_at" is null and "customers"."status" in ('lead', 'active');--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_service_order_idx" ON "reports" USING btree ("service_order_id") WHERE "reports"."service_order_id" is not null;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_status_check" CHECK ("reports"."status" in ('pending', 'created', 'in-progress', 'finished', 'mailed', 'cancelled'));