-- Contracts module (13 §1, document-artifact model of 2026-07-24): the stored
-- signed document + typed metadata + validity dates, generated by a service
-- order (0..n) or standalone. `file_key` is a PRIVATE R2 key — downloads stream
-- through GET /contracts/:id/file, so there is deliberately no public URL
-- column. Guards make it safe to re-run.
--
-- NOTE: the guards mean this is a no-op on a database that already carries an
-- older `contracts` table. The shared dev Neon DB has one hand-applied from the
-- superseded 2026-07-22 spec and must be dropped before migrating.
CREATE TABLE IF NOT EXISTS "contract_counters" (
	"day" date PRIMARY KEY NOT NULL,
	"last_number" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "contracts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"folio" text NOT NULL,
	"customer_id" uuid NOT NULL,
	"service_order_id" uuid,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"description" text,
	"file_key" text NOT NULL,
	"file_name" text NOT NULL,
	"file_type" text NOT NULL,
	"file_mime" text NOT NULL,
	"file_size" integer,
	"visible_to_roles" text[] DEFAULT '{office,technician}'::text[] NOT NULL,
	"valid_from_date" date NOT NULL,
	"expiry_date" date,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"created_by" uuid NOT NULL,
	"delete_comment" text,
	"deleted_by" uuid,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contracts_type_check" CHECK ("contracts"."type" in ('programmed_maintenance', 'corrective_maintenance', 'preventive_maintenance', 'installation', 'rent', 'sell', 'buy', 'guarantee')),
	CONSTRAINT "contracts_file_type_check" CHECK ("contracts"."file_type" in ('pdf', 'docx', 'odt', 'xls', 'xlsx'))
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "contracts" ADD CONSTRAINT "contracts_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "contracts" ADD CONSTRAINT "contracts_service_order_id_service_orders_id_fk" FOREIGN KEY ("service_order_id") REFERENCES "public"."service_orders"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "contracts" ADD CONSTRAINT "contracts_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "contracts" ADD CONSTRAINT "contracts_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "contracts_folio_uidx" ON "contracts" USING btree ("folio");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_customer_idx" ON "contracts" USING btree ("customer_id") WHERE "contracts"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_order_idx" ON "contracts" USING btree ("service_order_id") WHERE "contracts"."service_order_id" is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_tags_gin_idx" ON "contracts" USING gin ("tags");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_visible_roles_gin_idx" ON "contracts" USING gin ("visible_to_roles");